name: easy_camera
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/TheinvinciblePrints/easy_camera

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  camera: ^0.10.5+9
  image_editor: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codewithemmany.easy_camera
        pluginClass: EasyCameraPlugin
      ios:
        pluginClass: EasyCameraPlugin
