name: flutter_easy_camera
description: "EasyCamera is a Flutter plugin for seamless camera integration,
  offering customizable settings, preview styles, and intuitive controls for
  capturing images."
version: 0.0.7
homepage: https://github.com/TheinvinciblePrints/easy_camera

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  camera: ^0.10.6
  flutter:
    sdk: flutter
  image_editor: ^1.6.0
  native_device_orientation: ^2.0.3
  photo_view: ^0.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
